# Generated by Django 5.1.5 on 2025-02-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProjet2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateurs',
            managers=[
            ],
        ),
    ]
