# Generated by Django 5.1.5 on 2025-03-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjet2', '0002_alter_utilisateurs_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='taches',
            name='parent_tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='appProjet2.taches'),
        ),
    ]
