# Generated by Django 5.1.5 on 2025-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjet2', '0003_taches_parent_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projets',
            name='statut_projet',
            field=models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('En Attente', 'En attente')], max_length=20, null=True),
        ),
    ]
