# Generated by Django 5.1.5 on 2025-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjet2', '0005_alter_projets_statut_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='statut_tache',
            field=models.CharField(blank=True, choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('Terminée', 'Terminée')], max_length=20, null=True),
        ),
    ]
