# Generated by Django 5.1.5 on 2025-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjet2', '0006_alter_taches_statut_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('ChefProjet', 'Chef de Projet'), ('Employe', 'Employé'), ('UserStandard', 'UserStandard')], default='Employe', max_length=20),
        ),
    ]
