# Generated by Django 5.1.5 on 2025-03-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjet2', '0007_alter_utilisateurs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='parent_tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_taches', to='appProjet2.taches'),
        ),
    ]
